// <auto-generated />
using System;
using MarketApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarketApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarketApp.Domain.Entity.Inventory.StockBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AveragePurchaseUnitCost")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid>("InventoryLocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("InventoryLocationId");

                    b.HasIndex("ProductId", "InventoryLocationId")
                        .IsUnique()
                        .HasDatabaseName("UX_StockBalances_Product_Location");

                    b.ToTable("StockBalances", null, t =>
                        {
                            t.HasCheckConstraint("CK_BalanceCost_Nonnegative", "\"AveragePurchaseUnitCost\" >= 0");

                            t.HasCheckConstraint("CK_StockBalances_Quantity_NonNegative", "\"Quantity\" >= 0");
                        });
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Inventory.StockCostHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AveragePurchaseUnitCost")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid?>("ClientChangeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EffectiveAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InventoryLocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityAtChange")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("RecordedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ClientChangeId")
                        .IsUnique();

                    b.HasIndex("InventoryLocationId");

                    b.HasIndex("RecordedByUserId");

                    b.HasIndex("ProductId", "InventoryLocationId", "EffectiveAtUtc", "Id");

                    b.ToTable("StockCostHistories", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockCostHistory_Values", "\"AveragePurchaseUnitCost\" >= 0 AND \"QuantityAtChange\" >= 0");
                        });
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Inventory.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("InventoryLocationId")
                        .HasColumnType("uuid");

                    b.Property<int>("MovementType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PurchaseInvoiceLineId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityChange")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid?>("SalesInvoiceLineId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SalesReturnLineId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StockAdjustmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StockTransferLineId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InventoryLocationId");

                    b.HasIndex("PurchaseInvoiceLineId")
                        .IsUnique()
                        .HasDatabaseName("UX_StockMovements_PurchaseInvoiceLine")
                        .HasFilter("\"PurchaseInvoiceLineId\" IS NOT NULL");

                    b.HasIndex("SalesInvoiceLineId")
                        .IsUnique()
                        .HasDatabaseName("UX_StockMovements_SalesInvoiceLine")
                        .HasFilter("\"SalesInvoiceLineId\" IS NOT NULL");

                    b.HasIndex("SalesReturnLineId")
                        .IsUnique()
                        .HasFilter("\"SalesReturnLineId\" IS NOT NULL");

                    b.HasIndex("StockAdjustmentId")
                        .IsUnique()
                        .HasFilter("\"StockAdjustmentId\" IS NOT NULL");

                    b.HasIndex("StockTransferLineId", "MovementType")
                        .IsUnique()
                        .HasDatabaseName("UX_StockMovements_TransferLine_Type")
                        .HasFilter("\"StockTransferLineId\" IS NOT NULL");

                    b.HasIndex("ProductId", "InventoryLocationId", "OccurredAtUtc", "Id")
                        .HasDatabaseName("IX_StockMovements_Product_Location_History");

                    b.ToTable("StockMovements", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockMovements_Source", "num_nonnulls(\"PurchaseInvoiceLineId\", \"StockTransferLineId\", \"SalesInvoiceLineId\", \"SalesReturnLineId\", \"StockAdjustmentId\") = 1 AND (\r\n(\"MovementType\" = 1 AND \"PurchaseInvoiceLineId\" IS NOT NULL)\r\nOR (\"MovementType\" IN (2, 3, 4) AND \"StockTransferLineId\" IS NOT NULL)\r\nOR (\"MovementType\" = 5 AND \"SalesInvoiceLineId\" IS NOT NULL)\r\nOR (\"MovementType\" = 6 AND \"SalesReturnLineId\" IS NOT NULL)\r\nOR (\"MovementType\" = 7 AND \"StockAdjustmentId\" IS NOT NULL))");

                            t.HasCheckConstraint("CK_StockMovements_TypeAndQuantity", "(\"MovementType\" IN (1, 3, 4, 6) AND \"QuantityChange\" > 0) OR (\"MovementType\" IN (2, 5) AND \"QuantityChange\" < 0) OR (\"MovementType\" = 7 AND \"QuantityChange\" <> 0)");
                        });
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Inventory.StockTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DestinationLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReturnReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ReturnRequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReturnedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ShippedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SourceLocationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("DestinationLocationId");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("SourceLocationId");

                    b.ToTable("StockTransfers", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockTransfers_DifferentLocations", "\"SourceLocationId\" <> \"DestinationLocationId\"");

                            t.HasCheckConstraint("CK_StockTransfers_ReturnDetails", "(\"Status\" IN (1, 2, 3, 4) AND \"ReturnRequestedAtUtc\" IS NULL AND \"ReturnedAtUtc\" IS NULL AND \"ReturnReason\" IS NULL) OR (\"Status\" = 5 AND \"ReturnRequestedAtUtc\" IS NOT NULL AND \"ReturnRequestedAtUtc\" >= \"ShippedAtUtc\" AND \"ReturnedAtUtc\" IS NULL AND \"ReturnReason\" IS NOT NULL AND length(btrim(\"ReturnReason\")) > 0) OR (\"Status\" = 6 AND \"ReturnRequestedAtUtc\" IS NOT NULL AND \"ReturnRequestedAtUtc\" >= \"ShippedAtUtc\" AND \"ReturnedAtUtc\" IS NOT NULL AND \"ReturnedAtUtc\" >= \"ReturnRequestedAtUtc\" AND \"ReturnReason\" IS NOT NULL AND length(btrim(\"ReturnReason\")) > 0)");

                            t.HasCheckConstraint("CK_StockTransfers_Status", "\"Status\" IN (1, 2, 3, 4, 5, 6)");

                            t.HasCheckConstraint("CK_StockTransfers_StatusTimestamps", "(\"Status\" IN (1, 4) AND \"ShippedAtUtc\" IS NULL AND \"ReceivedAtUtc\" IS NULL) OR (\"Status\" IN (2, 5, 6) AND \"ShippedAtUtc\" IS NOT NULL AND \"ReceivedAtUtc\" IS NULL) OR (\"Status\" = 3 AND \"ShippedAtUtc\" IS NOT NULL AND \"ReceivedAtUtc\" IS NOT NULL AND \"ReceivedAtUtc\" >= \"ShippedAtUtc\")");
                        });
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Inventory.StockTransferLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("BaselineRevisionAtCreation")
                        .HasColumnType("integer");

                    b.Property<decimal>("BaselineUnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("PurchaseUnitCostSnapshot")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid>("StockTransferId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockTransferId", "LineNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_StockTransferLines_Transfer_Line");

                    b.ToTable("StockTransferLines", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockTransferLines_BaselineRevisionAtCreation", "\"BaselineRevisionAtCreation\" IS NULL OR \"BaselineRevisionAtCreation\" >= 0");

                            t.HasCheckConstraint("CK_StockTransferLines_BaselineUnitPrice", "\"BaselineUnitPrice\" >= 0");

                            t.HasCheckConstraint("CK_StockTransferLines_LineNumber", "\"LineNumber\" > 0");

                            t.HasCheckConstraint("CK_StockTransferLines_Quantity", "\"Quantity\" > 0");

                            t.HasCheckConstraint("CK_TransferCost_Nonnegative", "\"PurchaseUnitCostSnapshot\" >= 0");
                        });
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Main.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Branches", (string)null);
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Main.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Main.InventoryLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("InventoryLocations", (string)null);
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Main.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Main.ProductPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsReady")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("UX_ProductPhotos_StorageKey");

                    b.HasIndex("IsReady", "DeletedAtUtc", "CreatedAtUtc");

                    b.HasIndex("ProductId", "SortOrder", "Id");

                    b.ToTable("ProductPhotos", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProductPhotos_ContentHash", "\"ContentHash\" ~ '^[0-9A-F]{64}$'");

                            t.HasCheckConstraint("CK_ProductPhotos_ContentType", "\"ContentType\" IN ('image/jpeg', 'image/png', 'image/webp')");

                            t.HasCheckConstraint("CK_ProductPhotos_FileSizeBytes", "\"FileSizeBytes\" > 0");

                            t.HasCheckConstraint("CK_ProductPhotos_SortOrder", "\"SortOrder\" >= 0");

                            t.HasCheckConstraint("CK_ProductPhotos_StorageKey", "length(btrim(\"StorageKey\")) > 0");
                        });
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Main.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Pricing.BranchProductPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BaselineRevision")
                        .HasColumnType("integer");

                    b.Property<decimal?>("BaselineUnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("MinimumSellingPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("BranchId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("UX_BranchProductPrices_Branch_Product");

                    b.ToTable("BranchProductPrices", null, t =>
                        {
                            t.HasCheckConstraint("CK_BranchProductPrices_Baseline", "\"BaselineUnitPrice\" IS NULL OR \"BaselineUnitPrice\" >= 0");

                            t.HasCheckConstraint("CK_BranchProductPrices_BaselineRevision", "\"BaselineRevision\" >= 0 AND \"BaselineRevision\" <= \"Revision\" AND ((\"BaselineUnitPrice\" IS NULL AND \"BaselineRevision\" = 0) OR (\"BaselineUnitPrice\" IS NOT NULL AND \"BaselineRevision\" > 0))");

                            t.HasCheckConstraint("CK_BranchProductPrices_HasPrice", "\"BaselineUnitPrice\" IS NOT NULL OR \"MinimumSellingPrice\" IS NOT NULL");

                            t.HasCheckConstraint("CK_BranchProductPrices_Minimum", "\"MinimumSellingPrice\" IS NULL OR \"MinimumSellingPrice\" >= 0");

                            t.HasCheckConstraint("CK_BranchProductPrices_Revision", "\"Revision\" > 0");
                        });
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Pricing.BranchProductPriceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchProductPriceId")
                        .HasColumnType("uuid");

                    b.Property<int>("ChangeType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("NewBaselineUnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("NewMinimumSellingPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("OldBaselineUnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("OldMinimumSellingPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<Guid?>("StockTransferLineId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StockTransferLineId");

                    b.HasIndex("BranchProductPriceId", "Revision")
                        .IsUnique()
                        .HasDatabaseName("UX_BranchPriceHistory_Price_Revision");

                    b.ToTable("BranchProductPriceHistory", null, t =>
                        {
                            t.HasCheckConstraint("CK_BranchPriceHistory_HasNewPrice", "\"NewBaselineUnitPrice\" IS NOT NULL OR \"NewMinimumSellingPrice\" IS NOT NULL");

                            t.HasCheckConstraint("CK_BranchPriceHistory_Prices", "(\"OldBaselineUnitPrice\" IS NULL OR \"OldBaselineUnitPrice\" >= 0) AND (\"NewBaselineUnitPrice\" IS NULL OR \"NewBaselineUnitPrice\" >= 0) AND (\"OldMinimumSellingPrice\" IS NULL OR \"OldMinimumSellingPrice\" >= 0) AND (\"NewMinimumSellingPrice\" IS NULL OR \"NewMinimumSellingPrice\" >= 0)");

                            t.HasCheckConstraint("CK_BranchPriceHistory_Reason", "length(btrim(\"Reason\")) > 0");

                            t.HasCheckConstraint("CK_BranchPriceHistory_Revision", "\"Revision\" > 0");

                            t.HasCheckConstraint("CK_BranchPriceHistory_Source", "(\"ChangeType\" IN (1, 2) AND \"StockTransferLineId\" IS NULL) OR (\"ChangeType\" = 3 AND \"StockTransferLineId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Purchasing.PurchaseInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InventoryLocationId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("PostedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<string>("SupplierInvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("InventoryLocationId");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("PurchaseInvoices", null, t =>
                        {
                            t.HasCheckConstraint("CK_PurchaseInvoices_PostedAt", "(\"Status\" = 1 AND \"PostedAtUtc\" IS NULL) OR (\"Status\" = 2 AND \"PostedAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_PurchaseInvoices_Status", "\"Status\" IN (1, 2)");
                        });
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Purchasing.PurchaseInvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseInvoiceId", "LineNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_PurchaseInvoiceLines_Invoice_Line");

                    b.ToTable("PurchaseInvoiceLines", null, t =>
                        {
                            t.HasCheckConstraint("CK_PurchaseInvoiceLines_LineNumber", "\"LineNumber\" > 0");

                            t.HasCheckConstraint("CK_PurchaseInvoiceLines_Quantity", "\"Quantity\" > 0");

                            t.HasCheckConstraint("CK_PurchaseInvoiceLines_UnitCost", "\"UnitCost\" >= 0");
                        });
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Sales.BranchExpense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ClientExpenseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("EmployeeUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("VoidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VoidedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("EmployeeUserId");

                    b.HasIndex("VoidedByUserId");

                    b.HasIndex("BranchId", "ClientExpenseId")
                        .IsUnique();

                    b.HasIndex("BranchId", "OccurredAtUtc", "Id");

                    b.ToTable("BranchExpenses", null, t =>
                        {
                            t.HasCheckConstraint("CK_BranchExpense_Amount", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_BranchExpense_Category", "\"Category\" IN ('Salary','Rent','Other')");

                            t.HasCheckConstraint("CK_BranchExpense_Void", "(\"VoidedAtUtc\" IS NULL AND \"VoidedByUserId\" IS NULL AND \"VoidReason\" IS NULL) OR\r\n(\"VoidedAtUtc\" IS NOT NULL AND \"VoidedByUserId\" IS NOT NULL AND \"VoidReason\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Sales.ManagerProfitShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientChangeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ManagerUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Percent")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ManagerUserId");

                    b.HasIndex("BranchId", "ClientChangeId")
                        .IsUnique();

                    b.HasIndex("BranchId", "EffectiveFromUtc")
                        .IsUnique();

                    b.ToTable("ManagerProfitShares", null, t =>
                        {
                            t.HasCheckConstraint("CK_ManagerShare_Percent", "\"Percent\" BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Sales.SalesInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientSaleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InventoryLocationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOffline")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ManagerSharePercentSnapshot")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.Property<Guid?>("ManagerUserIdSnapshot")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("ReconciledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReconciledByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("SoldAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SoldByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InventoryLocationId");

                    b.HasIndex("ManagerUserIdSnapshot");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("ReconciledByUserId");

                    b.HasIndex("SoldByUserId");

                    b.HasIndex("BranchId", "ClientSaleId")
                        .IsUnique();

                    b.HasIndex("BranchId", "SoldAtUtc", "Id");

                    b.ToTable("SalesInvoices", null, t =>
                        {
                            t.HasCheckConstraint("CK_SalesInvoices_ManagerShare", "\"ManagerSharePercentSnapshot\" BETWEEN 0 AND 100 AND\r\n(\"ManagerUserIdSnapshot\" IS NOT NULL OR \"ManagerSharePercentSnapshot\" = 0)");

                            t.HasCheckConstraint("CK_SalesInvoices_Reconciliation", "(\"ReconciledByUserId\" IS NULL AND \"ReconciledAtUtc\" IS NULL) OR\r\n(\"ReconciledByUserId\" IS NOT NULL AND \"ReconciledAtUtc\" IS NOT NULL AND \"IsOffline\")");
                        });
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Sales.SalesInvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BaselineUnitPriceSnapshot")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("MinimumSellingPriceSnapshot")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("PriceRevisionSnapshot")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProductSkuSnapshot")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PurchaseCostReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PurchaseCostRecordHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("PurchaseCostRecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PurchaseCostRecordedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("PurchaseUnitCostSnapshot")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("ReturnedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid>("SalesInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SellingUnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseCostRecordedByUserId");

                    b.HasIndex("SalesInvoiceId", "LineNumber")
                        .IsUnique();

                    b.HasIndex("SalesInvoiceId", "ProductId")
                        .IsUnique();

                    b.ToTable("SalesInvoiceLines", null, t =>
                        {
                            t.HasCheckConstraint("CK_SaleCost_Nonnegative", "\"PurchaseUnitCostSnapshot\" >= 0");

                            t.HasCheckConstraint("CK_SalesLines_Price", "\"BaselineUnitPriceSnapshot\" >= 0 AND \"MinimumSellingPriceSnapshot\" >= 0 AND \"SellingUnitPrice\" >= \"MinimumSellingPriceSnapshot\"");

                            t.HasCheckConstraint("CK_SalesLines_Quantity", "\"Quantity\" > 0 AND \"ReturnedQuantity\" >= 0 AND \"ReturnedQuantity\" <= \"Quantity\"");

                            t.HasCheckConstraint("CK_SalesLines_Sequence", "\"LineNumber\" > 0 AND \"PriceRevisionSnapshot\" > 0");
                        });
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Sales.SalesReturn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientReturnId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("SalesInvoiceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("SalesInvoiceId");

                    b.HasIndex("BranchId", "ClientReturnId")
                        .IsUnique();

                    b.HasIndex("BranchId", "CreatedAtUtc", "Id");

                    b.ToTable("SalesReturns");
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Sales.SalesReturnLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<bool>("Restock")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SalesInvoiceLineId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SalesReturnId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SalesInvoiceLineId");

                    b.HasIndex("SalesReturnId", "SalesInvoiceLineId")
                        .IsUnique();

                    b.ToTable("SalesReturnLines", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReturnLines_Quantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Sales.StockAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientAdjustmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InventoryLocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityChange")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ClientAdjustmentId")
                        .IsUnique();

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("InventoryLocationId");

                    b.HasIndex("ProductId");

                    b.HasIndex("CreatedAtUtc", "Id");

                    b.ToTable("StockAdjustments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Adjustments_Quantity", "\"QuantityChange\" <> 0");
                        });
                });

            modelBuilder.Entity("MarketApp.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MarketApp.Infrastructure.Identity.ApplicationUserBranch", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "BranchId");

                    b.HasIndex("BranchId");

                    b.ToTable("UserBranchAssignments", (string)null);
                });

            modelBuilder.Entity("MarketApp.Infrastructure.Identity.AuthSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastRefreshedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_AuthSessions_Expiry");

                    b.HasIndex("UserId", "ExpiresAtUtc")
                        .HasDatabaseName("IX_AuthSessions_User_Expiry");

                    b.ToTable("AuthSessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_AuthSessions_Expiry", "\"ExpiresAtUtc\" > \"CreatedAtUtc\"");

                            t.HasCheckConstraint("CK_AuthSessions_LastRefresh", "\"LastRefreshedAtUtc\" IS NULL OR \"LastRefreshedAtUtc\" >= \"CreatedAtUtc\"");

                            t.HasCheckConstraint("CK_AuthSessions_Revocation", "\"RevokedAtUtc\" IS NULL OR \"RevokedAtUtc\" >= \"CreatedAtUtc\"");

                            t.HasCheckConstraint("CK_AuthSessions_SecurityStamp", "length(btrim(\"SecurityStamp\")) > 0");
                        });
                });

            modelBuilder.Entity("MarketApp.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_RefreshTokens_TokenHash");

                    b.HasIndex("AuthSessionId", "CreatedAtUtc")
                        .HasDatabaseName("IX_RefreshTokens_Session_Created");

                    b.ToTable("RefreshTokens", null, t =>
                        {
                            t.HasCheckConstraint("CK_RefreshTokens_Consumption", "\"ConsumedAtUtc\" IS NULL OR \"ConsumedAtUtc\" >= \"CreatedAtUtc\"");

                            t.HasCheckConstraint("CK_RefreshTokens_Expiry", "\"ExpiresAtUtc\" > \"CreatedAtUtc\"");

                            t.HasCheckConstraint("CK_RefreshTokens_Hash", "\"TokenHash\" ~ '^[0-9A-F]{64}$'");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Inventory.StockBalance", b =>
                {
                    b.HasOne("MarketApp.Domain.Entity.Main.InventoryLocation", "InventoryLocation")
                        .WithMany()
                        .HasForeignKey("InventoryLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketApp.Domain.Entity.Main.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InventoryLocation");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Inventory.StockCostHistory", b =>
                {
                    b.HasOne("MarketApp.Domain.Entity.Main.InventoryLocation", null)
                        .WithMany()
                        .HasForeignKey("InventoryLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketApp.Domain.Entity.Main.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Inventory.StockMovement", b =>
                {
                    b.HasOne("MarketApp.Domain.Entity.Main.InventoryLocation", "InventoryLocation")
                        .WithMany()
                        .HasForeignKey("InventoryLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketApp.Domain.Entity.Main.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketApp.Domain.Entity.Purchasing.PurchaseInvoiceLine", "PurchaseInvoiceLine")
                        .WithMany()
                        .HasForeignKey("PurchaseInvoiceLineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MarketApp.Domain.Entity.Sales.SalesInvoiceLine", "SalesInvoiceLine")
                        .WithMany()
                        .HasForeignKey("SalesInvoiceLineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MarketApp.Domain.Entity.Sales.SalesReturnLine", "SalesReturnLine")
                        .WithMany()
                        .HasForeignKey("SalesReturnLineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MarketApp.Domain.Entity.Sales.StockAdjustment", "StockAdjustment")
                        .WithMany()
                        .HasForeignKey("StockAdjustmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MarketApp.Domain.Entity.Inventory.StockTransferLine", "StockTransferLine")
                        .WithMany()
                        .HasForeignKey("StockTransferLineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("InventoryLocation");

                    b.Navigation("Product");

                    b.Navigation("PurchaseInvoiceLine");

                    b.Navigation("SalesInvoiceLine");

                    b.Navigation("SalesReturnLine");

                    b.Navigation("StockAdjustment");

                    b.Navigation("StockTransferLine");
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Inventory.StockTransfer", b =>
                {
                    b.HasOne("MarketApp.Domain.Entity.Main.InventoryLocation", "DestinationLocation")
                        .WithMany()
                        .HasForeignKey("DestinationLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketApp.Domain.Entity.Main.InventoryLocation", "SourceLocation")
                        .WithMany()
                        .HasForeignKey("SourceLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationLocation");

                    b.Navigation("SourceLocation");
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Inventory.StockTransferLine", b =>
                {
                    b.HasOne("MarketApp.Domain.Entity.Main.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketApp.Domain.Entity.Inventory.StockTransfer", "StockTransfer")
                        .WithMany("Lines")
                        .HasForeignKey("StockTransferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("StockTransfer");
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Main.InventoryLocation", b =>
                {
                    b.HasOne("MarketApp.Domain.Entity.Main.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Main.Product", b =>
                {
                    b.HasOne("MarketApp.Domain.Entity.Main.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Main.ProductPhoto", b =>
                {
                    b.HasOne("MarketApp.Domain.Entity.Main.Product", "Product")
                        .WithMany("Photos")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Pricing.BranchProductPrice", b =>
                {
                    b.HasOne("MarketApp.Domain.Entity.Main.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketApp.Domain.Entity.Main.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Pricing.BranchProductPriceHistory", b =>
                {
                    b.HasOne("MarketApp.Domain.Entity.Pricing.BranchProductPrice", "BranchProductPrice")
                        .WithMany()
                        .HasForeignKey("BranchProductPriceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketApp.Domain.Entity.Inventory.StockTransferLine", "StockTransferLine")
                        .WithMany()
                        .HasForeignKey("StockTransferLineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BranchProductPrice");

                    b.Navigation("StockTransferLine");
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Purchasing.PurchaseInvoice", b =>
                {
                    b.HasOne("MarketApp.Domain.Entity.Main.InventoryLocation", "InventoryLocation")
                        .WithMany()
                        .HasForeignKey("InventoryLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketApp.Domain.Entity.Main.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InventoryLocation");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Purchasing.PurchaseInvoiceLine", b =>
                {
                    b.HasOne("MarketApp.Domain.Entity.Main.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketApp.Domain.Entity.Purchasing.PurchaseInvoice", "PurchaseInvoice")
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("PurchaseInvoice");
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Sales.BranchExpense", b =>
                {
                    b.HasOne("MarketApp.Domain.Entity.Main.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("EmployeeUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MarketApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("VoidedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Sales.ManagerProfitShare", b =>
                {
                    b.HasOne("MarketApp.Domain.Entity.Main.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ManagerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Sales.SalesInvoice", b =>
                {
                    b.HasOne("MarketApp.Domain.Entity.Main.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketApp.Domain.Entity.Main.InventoryLocation", "InventoryLocation")
                        .WithMany()
                        .HasForeignKey("InventoryLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ManagerUserIdSnapshot")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MarketApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ReconciledByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MarketApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("SoldByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("InventoryLocation");
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Sales.SalesInvoiceLine", b =>
                {
                    b.HasOne("MarketApp.Domain.Entity.Main.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("PurchaseCostRecordedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MarketApp.Domain.Entity.Sales.SalesInvoice", "SalesInvoice")
                        .WithMany("Lines")
                        .HasForeignKey("SalesInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SalesInvoice");
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Sales.SalesReturn", b =>
                {
                    b.HasOne("MarketApp.Domain.Entity.Main.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketApp.Domain.Entity.Sales.SalesInvoice", "SalesInvoice")
                        .WithMany()
                        .HasForeignKey("SalesInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("SalesInvoice");
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Sales.SalesReturnLine", b =>
                {
                    b.HasOne("MarketApp.Domain.Entity.Sales.SalesInvoiceLine", "SalesInvoiceLine")
                        .WithMany()
                        .HasForeignKey("SalesInvoiceLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketApp.Domain.Entity.Sales.SalesReturn", "SalesReturn")
                        .WithMany("Lines")
                        .HasForeignKey("SalesReturnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SalesInvoiceLine");

                    b.Navigation("SalesReturn");
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Sales.StockAdjustment", b =>
                {
                    b.HasOne("MarketApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketApp.Domain.Entity.Main.InventoryLocation", "InventoryLocation")
                        .WithMany()
                        .HasForeignKey("InventoryLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketApp.Domain.Entity.Main.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InventoryLocation");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MarketApp.Infrastructure.Identity.ApplicationUserBranch", b =>
                {
                    b.HasOne("MarketApp.Domain.Entity.Main.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketApp.Infrastructure.Identity.ApplicationUser", "User")
                        .WithMany("BranchAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MarketApp.Infrastructure.Identity.AuthSession", b =>
                {
                    b.HasOne("MarketApp.Infrastructure.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MarketApp.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.HasOne("MarketApp.Infrastructure.Identity.AuthSession", "AuthSession")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AuthSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuthSession");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MarketApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MarketApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MarketApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Inventory.StockTransfer", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Main.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Main.Product", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Purchasing.PurchaseInvoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Sales.SalesInvoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("MarketApp.Domain.Entity.Sales.SalesReturn", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("MarketApp.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Navigation("BranchAssignments");
                });

            modelBuilder.Entity("MarketApp.Infrastructure.Identity.AuthSession", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
