<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="4.153.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="4.153.1" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.104.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.12" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
	  <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
	
	
  <ItemGroup>
    <ProjectReference Include="..\MarketApp.Domain\MarketApp.Domain.csproj" />
    <ProjectReference Include="..\MarketApp.Application\MarketApp.Application.csproj" />
  </ItemGroup>
	

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
